// Generated by CoffeeScript 1.7.1
var hide_charts, is_descendant, mark_all, set_textarea_line, set_textbox, switch_tab, switch_to, togHTML, toggle_form, togvis, togvis_div, togvis_span, togvis_tbody;

is_descendant = function(par, child) {
  var node;
  node = child;
  while (node != null) {
    if (node === par) {
      return true;
    } else {
      node = node.parentNode;
    }
  }
  return false;
};

set_textbox = function(id, s) {
  return $("#" + id)[0].value = s;
};

set_textarea_line = function(id, s, line) {
  var a, cur;
  cur = $("#" + id)[0].value.replace(/\r\n/, '\n');
  a = cur.split('\n');
  a[line] = s;
  return $("#" + id)[0].value = a.join('\n');
};

togvis = function(id, visible) {
  return $("#" + id).toggle();
};

togvis_tbody = function(id) {
  return togvis(id);
};

togvis_span = togvis_tbody;

togvis_div = togvis_span;

switch_to = function(id, all) {
  var cid, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = all.length; _i < _len; _i++) {
    cid = all[_i];
    if (cid === id) {
      _results.push($("#" + cid).show());
    } else {
      _results.push($("#" + cid).hide());
    }
  }
  return _results;
};

switch_tab = function(id, all) {
  var tabid, _i, _len, _results;
  _results = [];
  for (_i = 0, _len = all.length; _i < _len; _i++) {
    tabid = all[_i];
    if (tabid === id) {
      $("#" + tabid).show();
      _results.push($("#" + tabid + "-tab").attr('class', 'tabsel'));
    } else {
      $("#" + tabid).hide();
      _results.push($("#" + tabid + "-tab").attr('class', 'tabunsel'));
    }
  }
  return _results;
};

toggle_form = function(id) {
  return $("#" + id).show();
};

hide_charts = function() {
  return $("#chart").hide();
};

togHTML = function(id, a, b) {
  var d;
  d = $("#" + id);
  if (d.html().trim() === a) {
    return d.html(b);
  } else {
    return d.html(a);
  }
};

mark_all = function(val, prefix) {
  return $('input:checkbox').each(function(i, e) {
    if (prefix === '' || 0 === $(e).name.indexOf(prefix)) {
      return $(e).checked = val;
    }
  });
};
// Generated by CoffeeScript 1.7.1
var gen_short;

gen_short = function(path) {
  return $.get("/m/new/?url=" + encodeURIComponent(path), function(data) {
    $("#genshort").hide();
    $("#dispshort").html("<a href=\"/m/" + data + "/\">/m/" + data + "</a>");
    return $("#dispshort").show();
  });
};
// Generated by CoffeeScript 1.7.1
var mobile_regex;

mobile_regex = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|OperaMini/i;

$(function() {
  var allMenu, menuHandler;
  allMenu = $('.menu > ul > li > ul');
  menuHandler = function() {
    var menu;
    menu = $(this).parent().next();
    if (menu.is(':visible')) {
      allMenu.hide();
    } else {
      allMenu.hide();
      menu.show();
    }
    $(document).one('click', function() {
      return menu.hide();
    });
    return false;
  };
  if (mobile_regex.test(navigator.userAgent)) {
    $(".actionSelector").removeAttr("style");
    $('.menu > ul > li > div > a').next().button({
      text: false,
      icons: {
        primary: 'ui-icon-triangle-1-s'
      }
    }).click(menuHandler).parent().next().buttonset().hide().menu();
    return allMenu.parent().css({
      paddingLeft: "0.1em",
      paddingRight: "0.1em"
    });
  } else {
    return $('.menu > ul > li > div > a').hover(menuHandler).parent().next().buttonset().hide().menu();
  }
});
