/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Username = string;
export type Password = string;
export type Username1 = string;

export interface Schema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Schema`'s JSON-Schema
 * via the `definition` "LoginRequest".
 */
export interface LoginRequest {
  username: Username;
  password: Password;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `Schema`'s JSON-Schema
 * via the `definition` "LoginResponse".
 */
export interface LoginResponse {
  username: Username1;
  [k: string]: unknown;
}
