FROM python:3.12-slim

WORKDIR /backend

RUN python -m pip install --upgrade uv
COPY backend/src /backend/src
COPY backend/uv.lock /backend/uv.lock
COPY backend/pyproject.toml /backend/pyproject.toml
COPY backend/README.md /backend/README.md

RUN uv sync

CMD ["uv", "run", "litestar", "--app", "aligulac.server:create_app", "run", "-H", "0.0.0.0"]
