"""Legacy migration

Revision ID: 062140861a3e
Revises: 
Create Date: 2025-11-14 12:47:59.447663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '062140861a3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('date_opened', sa.Date(), nullable=False),
    sa.Column('organization', sa.String(), nullable=False),
    sa.Column('contact', sa.String(), nullable=False),
    sa.Column('requests', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('balanceentry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pvt_wins', sa.Integer(), nullable=False),
    sa.Column('pvt_losses', sa.Integer(), nullable=False),
    sa.Column('pvz_wins', sa.Integer(), nullable=False),
    sa.Column('pvz_losses', sa.Integer(), nullable=False),
    sa.Column('tvz_wins', sa.Integer(), nullable=False),
    sa.Column('tvz_losses', sa.Integer(), nullable=False),
    sa.Column('p_gains', sa.Float(), nullable=False),
    sa.Column('t_gains', sa.Float(), nullable=False),
    sa.Column('z_gains', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('blog_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=True),
    sa.Column('rgt', sa.Integer(), nullable=True),
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('closed', sa.Boolean(), nullable=False),
    sa.Column('big', sa.Boolean(), nullable=False),
    sa.Column('noprint', sa.Boolean(), nullable=False),
    sa.Column('fullname', sa.String(), nullable=False),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('lp_name', sa.String(), nullable=True),
    sa.Column('tlpd_id', sa.Integer(), nullable=True),
    sa.Column('tlpd_db', sa.Integer(), nullable=True),
    sa.Column('tl_thread', sa.Integer(), nullable=True),
    sa.Column('prizepool', sa.Boolean(), nullable=True),
    sa.Column('earliest', sa.Date(), nullable=True),
    sa.Column('latest', sa.Date(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('wcs_year', sa.Integer(), nullable=True),
    sa.Column('wcs_tier', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shortname', sa.String(), nullable=True),
    sa.Column('scoreak', sa.Float(), nullable=True),
    sa.Column('scorepl', sa.Float(), nullable=True),
    sa.Column('meanrating', sa.Float(), nullable=True),
    sa.Column('founded', sa.Date(), nullable=True),
    sa.Column('disbanded', sa.Date(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('lp_name', sa.String(), nullable=True),
    sa.Column('is_team', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('period',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=False),
    sa.Column('end', sa.Date(), nullable=False),
    sa.Column('computed', sa.Boolean(), nullable=False),
    sa.Column('needs_recompute', sa.Boolean(), nullable=False),
    sa.Column('num_retplayers', sa.Integer(), nullable=False),
    sa.Column('num_newplayers', sa.Integer(), nullable=False),
    sa.Column('num_games', sa.Integer(), nullable=False),
    sa.Column('dom_p', sa.Float(), nullable=True),
    sa.Column('dom_t', sa.Float(), nullable=True),
    sa.Column('dom_z', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('romanized_name', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('race', sa.String(), nullable=False),
    sa.Column('mcnum', sa.Integer(), nullable=True),
    sa.Column('tlpd_id', sa.Integer(), nullable=True),
    sa.Column('tlpd_db', sa.Integer(), nullable=True),
    sa.Column('lp_name', sa.String(), nullable=True),
    sa.Column('sc2e_id', sa.Integer(), nullable=True),
    sa.Column('current_rating_id', sa.Integer(), nullable=True),
    sa.Column('dom_val', sa.Float(), nullable=True),
    sa.Column('dom_start_id', sa.Integer(), nullable=True),
    sa.Column('dom_end_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prematchgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('offline', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('prev_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('rating_vp', sa.Float(), nullable=False),
    sa.Column('rating_vt', sa.Float(), nullable=False),
    sa.Column('rating_vz', sa.Float(), nullable=False),
    sa.Column('dev', sa.Float(), nullable=False),
    sa.Column('dev_vp', sa.Float(), nullable=False),
    sa.Column('dev_vt', sa.Float(), nullable=False),
    sa.Column('dev_vz', sa.Float(), nullable=False),
    sa.Column('comp_rat', sa.Float(), nullable=True),
    sa.Column('comp_rat_vp', sa.Float(), nullable=True),
    sa.Column('comp_rat_vt', sa.Float(), nullable=True),
    sa.Column('comp_rat_vz', sa.Float(), nullable=True),
    sa.Column('bf_rating', sa.Float(), nullable=False),
    sa.Column('bf_rating_vp', sa.Float(), nullable=False),
    sa.Column('bf_rating_vt', sa.Float(), nullable=False),
    sa.Column('bf_rating_vz', sa.Float(), nullable=False),
    sa.Column('bf_dev', sa.Float(), nullable=False),
    sa.Column('bf_dev_vp', sa.Float(), nullable=False),
    sa.Column('bf_dev_vt', sa.Float(), nullable=False),
    sa.Column('bf_dev_vz', sa.Float(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('position_vp', sa.Integer(), nullable=True),
    sa.Column('position_vt', sa.Integer(), nullable=True),
    sa.Column('position_vz', sa.Integer(), nullable=True),
    sa.Column('decay', sa.Integer(), nullable=False),
    sa.Column('domination', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('earnings', sa.Integer(), nullable=True),
    sa.Column('origearnings', sa.Numeric(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventadjacency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('distance', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groupmembership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('current', sa.Boolean(), nullable=False),
    sa.Column('playing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pla_id', sa.Integer(), nullable=False),
    sa.Column('plb_id', sa.Integer(), nullable=False),
    sa.Column('sca', sa.Integer(), nullable=False),
    sa.Column('scb', sa.Integer(), nullable=False),
    sa.Column('rca', sa.String(), nullable=False),
    sa.Column('rcb', sa.String(), nullable=False),
    sa.Column('treated', sa.Boolean(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('eventobj_id', sa.Integer(), nullable=True),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('game', sa.String(), nullable=False),
    sa.Column('offline', sa.Boolean(), nullable=False),
    sa.Column('rta_id', sa.Integer(), nullable=True),
    sa.Column('rtb_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('params', sa.String(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miniurl',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('longURL', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=True),
    sa.Column('nb_access', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prematch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('pla_id', sa.Integer(), nullable=True),
    sa.Column('plb_id', sa.Integer(), nullable=True),
    sa.Column('pla_string', sa.String(), nullable=True),
    sa.Column('plb_string', sa.String(), nullable=True),
    sa.Column('sca', sa.Integer(), nullable=False),
    sa.Column('scb', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rca', sa.String(), nullable=True),
    sa.Column('rcb', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('params', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wcspoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wcspoints')
    op.drop_table('story')
    op.drop_table('prematch')
    op.drop_table('miniurl')
    op.drop_table('message')
    op.drop_table('match')
    op.drop_table('groupmembership')
    op.drop_table('eventadjacency')
    op.drop_table('earnings')
    op.drop_table('alias')
    op.drop_table('rating')
    op.drop_table('prematchgroup')
    op.drop_table('player')
    op.drop_table('period')
    op.drop_table('group')
    op.drop_table('faq_post')
    op.drop_table('event')
    op.drop_table('blog_post')
    op.drop_table('balanceentry')
    op.drop_table('apikey')
    # ### end Alembic commands ###
