"""Re-add indexes

Revision ID: 398d0b19f80e
Revises: e732a2e373c3
Create Date: 2025-11-14 13:57:24.811236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '398d0b19f80e'
down_revision: Union[str, Sequence[str], None] = 'e732a2e373c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_event_category'), 'event', ['category'], unique=False)
    op.create_index(op.f('ix_event_closed'), 'event', ['closed'], unique=False)
    op.create_index(op.f('ix_event_earliest'), 'event', ['earliest'], unique=False)
    op.create_index(op.f('ix_event_idx'), 'event', ['idx'], unique=False)
    op.create_index(op.f('ix_event_latest'), 'event', ['latest'], unique=False)
    op.create_index(op.f('ix_event_noprint'), 'event', ['noprint'], unique=False)
    op.create_index(op.f('ix_event_prizepool'), 'event', ['prizepool'], unique=False)
    op.create_index(op.f('ix_event_type'), 'event', ['type'], unique=False)
    op.create_index(op.f('ix_eventadjacency_child_id'), 'eventadjacency', ['child_id'], unique=False)
    op.create_index(op.f('ix_eventadjacency_parent_id'), 'eventadjacency', ['parent_id'], unique=False)
    op.create_index(op.f('ix_group_active'), 'group', ['active'], unique=False)
    op.create_index(op.f('ix_group_is_team'), 'group', ['is_team'], unique=False)
    op.create_index(op.f('ix_group_name'), 'group', ['name'], unique=False)
    op.create_index(op.f('ix_groupmembership_current'), 'groupmembership', ['current'], unique=False)
    op.create_index(op.f('ix_groupmembership_playing'), 'groupmembership', ['playing'], unique=False)
    op.create_index(op.f('ix_match_game'), 'match', ['game'], unique=False)
    op.create_index(op.f('ix_match_offline'), 'match', ['offline'], unique=False)
    op.create_index(op.f('ix_match_rca'), 'match', ['rca'], unique=False)
    op.create_index(op.f('ix_match_rcb'), 'match', ['rcb'], unique=False)
    op.create_index(op.f('ix_match_sca'), 'match', ['sca'], unique=False)
    op.create_index(op.f('ix_match_scb'), 'match', ['scb'], unique=False)
    op.create_index(op.f('ix_period_computed'), 'period', ['computed'], unique=False)
    op.create_index(op.f('ix_period_end'), 'period', ['end'], unique=False)
    op.create_index(op.f('ix_period_needs_recompute'), 'period', ['needs_recompute'], unique=False)
    op.create_index(op.f('ix_period_start'), 'period', ['start'], unique=False)
    op.create_index(op.f('ix_player_country'), 'player', ['country'], unique=False)
    op.create_index(op.f('ix_player_race'), 'player', ['race'], unique=False)
    op.create_index(op.f('ix_player_tag'), 'player', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_player_tag'), table_name='player')
    op.drop_index(op.f('ix_player_race'), table_name='player')
    op.drop_index(op.f('ix_player_country'), table_name='player')
    op.drop_index(op.f('ix_period_start'), table_name='period')
    op.drop_index(op.f('ix_period_needs_recompute'), table_name='period')
    op.drop_index(op.f('ix_period_end'), table_name='period')
    op.drop_index(op.f('ix_period_computed'), table_name='period')
    op.drop_index(op.f('ix_match_scb'), table_name='match')
    op.drop_index(op.f('ix_match_sca'), table_name='match')
    op.drop_index(op.f('ix_match_rcb'), table_name='match')
    op.drop_index(op.f('ix_match_rca'), table_name='match')
    op.drop_index(op.f('ix_match_offline'), table_name='match')
    op.drop_index(op.f('ix_match_game'), table_name='match')
    op.drop_index(op.f('ix_groupmembership_playing'), table_name='groupmembership')
    op.drop_index(op.f('ix_groupmembership_current'), table_name='groupmembership')
    op.drop_index(op.f('ix_group_name'), table_name='group')
    op.drop_index(op.f('ix_group_is_team'), table_name='group')
    op.drop_index(op.f('ix_group_active'), table_name='group')
    op.drop_index(op.f('ix_eventadjacency_parent_id'), table_name='eventadjacency')
    op.drop_index(op.f('ix_eventadjacency_child_id'), table_name='eventadjacency')
    op.drop_index(op.f('ix_event_type'), table_name='event')
    op.drop_index(op.f('ix_event_prizepool'), table_name='event')
    op.drop_index(op.f('ix_event_noprint'), table_name='event')
    op.drop_index(op.f('ix_event_latest'), table_name='event')
    op.drop_index(op.f('ix_event_idx'), table_name='event')
    op.drop_index(op.f('ix_event_earliest'), table_name='event')
    op.drop_index(op.f('ix_event_closed'), table_name='event')
    op.drop_index(op.f('ix_event_category'), table_name='event')
    # ### end Alembic commands ###
