"""Add rating index

Revision ID: 3b117653434b
Revises: 398d0b19f80e
Create Date: 2025-11-19 15:57:13.878339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b117653434b'
down_revision: Union[str, Sequence[str], None] = '398d0b19f80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_rating_period_decay', 'rating', ['period_id', 'decay'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rating_period_decay', table_name='rating')
    # ### end Alembic commands ###
