"""Add blog index

Revision ID: 8e9505457f62
Revises: 3b117653434b
Create Date: 2025-11-24 12:51:04.380316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e9505457f62'
down_revision: Union[str, Sequence[str], None] = '3b117653434b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_blog_post_date', 'blog_post', [sa.literal_column('date DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_blog_post_date', table_name='blog_post')
    # ### end Alembic commands ###
