"""Legacy constraints

Revision ID: e732a2e373c3
Revises: 062140861a3e
Create Date: 2025-11-14 12:53:02.334680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e732a2e373c3'
down_revision: Union[str, Sequence[str], None] = '062140861a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'alias', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'alias', 'player', ['player_id'], ['id'])
    op.create_foreign_key(None, 'earnings', 'player', ['player_id'], ['id'])
    op.create_foreign_key(None, 'earnings', 'event', ['event_id'], ['id'])
    op.create_foreign_key(None, 'event', 'event', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'eventadjacency', 'event', ['child_id'], ['id'])
    op.create_foreign_key(None, 'eventadjacency', 'event', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'groupmembership', 'player', ['player_id'], ['id'])
    op.create_foreign_key(None, 'groupmembership', 'group', ['group_id'], ['id'])
    op.create_foreign_key(None, 'match', 'event', ['eventobj_id'], ['id'])
    op.create_foreign_key(None, 'match', 'period', ['period_id'], ['id'])
    op.create_foreign_key(None, 'match', 'player', ['plb_id'], ['id'])
    op.create_foreign_key(None, 'match', 'rating', ['rta_id'], ['id'])
    op.create_foreign_key(None, 'match', 'auth_user', ['submitter_id'], ['id'])
    op.create_foreign_key(None, 'match', 'player', ['pla_id'], ['id'])
    op.create_foreign_key(None, 'match', 'rating', ['rtb_id'], ['id'])
    op.create_foreign_key(None, 'message', 'player', ['event_id'], ['id'])
    op.create_foreign_key(None, 'message', 'player', ['group_id'], ['id'])
    op.create_foreign_key(None, 'message', 'player', ['player_id'], ['id'])
    op.create_foreign_key(None, 'message', 'player', ['match_id'], ['id'])
    op.create_foreign_key(None, 'miniurl', 'auth_user', ['submitter_id'], ['id'])
    op.create_foreign_key(None, 'player', 'period', ['dom_end_id'], ['id'])
    op.create_foreign_key(None, 'player', 'period', ['dom_start_id'], ['id'])
    op.create_foreign_key(None, 'player', 'rating', ['current_rating_id'], ['id'])
    op.create_foreign_key(None, 'prematch', 'prematchgroup', ['group_id'], ['id'])
    op.create_foreign_key(None, 'prematch', 'player', ['pla_id'], ['id'])
    op.create_foreign_key(None, 'prematch', 'player', ['plb_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'period', ['period_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'player', ['player_id'], ['id'])
    op.create_foreign_key(None, 'rating', 'rating', ['prev_id'], ['id'])
    op.create_foreign_key(None, 'story', 'player', ['player_id'], ['id'])
    op.create_foreign_key(None, 'story', 'event', ['event_id'], ['id'])
    op.create_foreign_key(None, 'wcspoints', 'event', ['event_id'], ['id'])
    op.create_foreign_key(None, 'wcspoints', 'player', ['player_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wcspoints', type_='foreignkey')
    op.drop_constraint(None, 'wcspoints', type_='foreignkey')
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_constraint(None, 'story', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'rating', type_='foreignkey')
    op.drop_constraint(None, 'prematch', type_='foreignkey')
    op.drop_constraint(None, 'prematch', type_='foreignkey')
    op.drop_constraint(None, 'prematch', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.drop_constraint(None, 'miniurl', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'groupmembership', type_='foreignkey')
    op.drop_constraint(None, 'groupmembership', type_='foreignkey')
    op.drop_constraint(None, 'eventadjacency', type_='foreignkey')
    op.drop_constraint(None, 'eventadjacency', type_='foreignkey')
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_constraint(None, 'earnings', type_='foreignkey')
    op.drop_constraint(None, 'earnings', type_='foreignkey')
    op.drop_constraint(None, 'alias', type_='foreignkey')
    op.drop_constraint(None, 'alias', type_='foreignkey')
    # ### end Alembic commands ###
